### ISSUE TITLE
那个github四步走能不能声明一下原作者

### ISSUE THREAD

**Issue by youngxhui** [swjtu-maker/webTeam#3]
github for windows在知乎上是禁止转载，既然你转载了，麻烦声明一下原作者，谢谢。

**我就是原作者**
😄

**Comment by lianglanzheng** [comment]
非常抱歉。
我已经在该条目后面声明了作者，如果还有不对的地方，欢迎指出。
如果其他方面有错误，也欢迎指出。
再次表示歉意。
